name: bi-python-kit
channels:
  - bioconda
  - conda-forge
dependencies:
  - bs4=4.12.3
  - numpy=1.26.4
  - pandas=2.1.3
  - pip=23.3.1
  - pytest=8.1.1
  - pip:
      - biopython==1.83
      - python-dotenv==1.0.1
      - requests==2.31.0
      - scikit-learn==1.3.2
